server:
  port: 8088
#   数据库数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root

  mail:
    # SMTP服务器
    host: smtp.qq.com
    # 发送验证码邮箱
    username: 984209872@qq.com
    # 授权码
    password: nrfmvbkumljdbbih
    # 编码
    default-encoding: utf-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  # Redis配置
  redis:
    host: localhost
    port: 6379
    # 根据自己设置的密码决定
    password: 123456
    # 操作0号数据库，默认有16个数据库
    database: 0
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: 1ms # 连接池最大阻塞等待时间
        max-idle: 4   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接



mybatis:
  mapper-locations: classpath:mapper/*.xml   #  xml文件
  #目的是为了省略resultType里的代码量
  type-aliases-package: com.example.springboot.pojo   #  别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl